import math
import os
import threading
import time


class HardwarePwmChannel:
    """A Linux PWM sysfs channel; all pulse edges are generated by hardware."""

    ROOT = "/sys/class/pwm"

    def __init__(self, chip, channel, period_ns, log_fn):
        self.log = log_fn
        self.chip = str(chip)
        self.channel = int(channel)
        self.period_ns = int(period_ns)
        self.chip_dir = os.path.join(self.ROOT, self.chip)
        self.channel_dir = os.path.join(self.chip_dir, f"pwm{self.channel}")
        self.owned = not os.path.isdir(self.channel_dir)

        if not os.path.isdir(self.chip_dir):
            raise FileNotFoundError(
                f"{self.chip_dir} fehlt; PWM-Overlay fuer GPIO12/13 aktivieren und Pi neu starten"
            )

        channel_count_path = os.path.join(self.chip_dir, "npwm")
        with open(channel_count_path, "r", encoding="ascii") as source:
            channel_count = int(source.read().strip())
        if not 0 <= self.channel < channel_count:
            raise ValueError(
                f"PWM-Kanal {self.channel} existiert nicht; {self.chip} hat {channel_count} Kanaele"
            )

        if self.owned:
            self._write("export", self.channel, self.chip_dir)
            deadline = time.monotonic() + 1.0
            while not os.path.isdir(self.channel_dir) and time.monotonic() < deadline:
                time.sleep(0.01)
            if not os.path.isdir(self.channel_dir):
                raise TimeoutError(f"PWM-Kanal {self.channel} wurde nicht exportiert")

        try:
            self._write("enable", 0, self.channel_dir)
            self._write("duty_cycle", 0, self.channel_dir)
            self._write("period", self.period_ns, self.channel_dir)
            self._write("enable", 1, self.channel_dir)
        except Exception:
            if self.owned:
                try:
                    self._write("unexport", self.channel, self.chip_dir)
                except OSError:
                    pass
            raise
        self.log(f"PWM initialisiert: {self.chip}/pwm{self.channel}, Periode={self.period_ns}ns")

    @staticmethod
    def _write(attribute, value, directory):
        path = os.path.join(directory, attribute)
        with open(path, "w", encoding="ascii") as target:
            target.write(str(value))

    def set_pulse_us(self, pulse_us):
        duty_ns = int(round(float(pulse_us) * 1000.0))
        if not 0 <= duty_ns <= self.period_ns:
            raise ValueError(f"PWM duty {duty_ns}ns ausserhalb der Periode {self.period_ns}ns")
        self._write("duty_cycle", duty_ns, self.channel_dir)

    def disable(self):
        self._write("duty_cycle", 0, self.channel_dir)

    def close(self):
        try:
            self._write("duty_cycle", 0, self.channel_dir)
            self._write("enable", 0, self.channel_dir)
        finally:
            if self.owned:
                try:
                    self._write("unexport", self.channel, self.chip_dir)
                except OSError as exc:
                    self.log(f"PWM unexport {self.channel} fehlgeschlagen: {exc}")


class ServoController:
    """Drives the positional SG-90 and timed continuous-rotation servo via hardware PWM."""

    def __init__(self, cfg=None, log_fn=None):
        cfg = cfg or {}
        self.log = log_fn or (lambda message: None)

        self.pulse_min_us = float(cfg.get("pulse_min_us", 500))
        self.pulse_max_us = float(cfg.get("pulse_max_us", 2400))
        self.angle_min = float(cfg.get("angle_min", 0))
        self.angle_max = float(cfg.get("angle_max", 180))
        self.frequency_hz = max(10, int(cfg.get("frequency_hz", 50)))
        self.period_ns = int(round(1_000_000_000 / self.frequency_hz))
        self.servo_settle_sec = max(0.0, float(cfg.get("move_settle_sec", 0.3)))
        self.first_move_settle_sec = max(0.0, float(cfg.get("first_move_settle_sec", 0.8)))
        self.release_after_move = bool(cfg.get("release_after_move", False))
        self.pwm_chip = str(cfg.get("pwm_chip", "pwmchip0"))
        self.default_speed_deg_per_sec = cfg.get("speed_deg_per_sec")

        servo1_cfg = cfg.get("servo1", {})
        servo2_cfg = cfg.get("servo2", {})
        eject_cfg = cfg.get("eject", {})
        load_cfg = cfg.get("load", {})

        self.servo1_stop_pulse_us = self._clamp_pulse(servo1_cfg.get("stop_pulse_us", 1500))
        self.servo1_eject_pulse_us = self._clamp_pulse(servo1_cfg.get("eject_pulse_us", 1600))
        self.servo1_load_pulse_us = self._clamp_pulse(servo1_cfg.get("load_pulse_us", 1400))
        self.servo1_eject_max_run_sec = max(
            0.1, float(eject_cfg.get("servo1_max_run_sec", 10.0))
        )
        self.servo1_load_max_run_sec = max(
            0.1, float(load_cfg.get("servo1_max_run_sec", 10.0))
        )

        self.servo2_closed_angle = float(servo2_cfg.get("closed_angle", 0))
        self.servo2_open_angle = float(servo2_cfg.get("open_angle", 90))
        self.servo2_speed_deg_per_sec = self._resolve_speed(servo2_cfg)
        self.servo2_smooth_ramp = bool(servo2_cfg.get("smooth_ramp", False))
        self.servo2_angle = None

        self.eject_door_delay_sec = max(0.0, float(eject_cfg.get("door_delay_sec", 0.4)))
        self.eject_door_open_hold_sec = max(0.0, float(eject_cfg.get("door_open_hold_sec", 3.0)))
        self.boot_step_delay_sec = max(0.0, float(eject_cfg.get("boot_step_delay_sec", 5.0)))

        self._lock = threading.Lock()
        self._busy = False
        self._sequence_label = ""
        self._load_switch_active = False
        self._load_switch_consumed = False
        self._load_neutral = threading.Event()
        self._load_neutral.set()
        self._load_endstop_active = False
        self._load_endstop = threading.Event()
        self._stop = threading.Event()
        self._worker = None
        self._servo1 = None
        self._servo2 = None

        try:
            self._servo1 = self._open_channel(servo1_cfg, "servo1")
            self._servo2 = self._open_channel(servo2_cfg, "servo2")
        except Exception:
            self.close()
            raise

    def _clamp_pulse(self, pulse_us):
        return max(self.pulse_min_us, min(self.pulse_max_us, float(pulse_us)))

    def _clamp_angle(self, angle):
        return max(self.angle_min, min(self.angle_max, float(angle)))

    def _resolve_speed(self, servo_cfg):
        speed = servo_cfg.get("speed_deg_per_sec", self.default_speed_deg_per_sec)
        return float(speed) if speed else None

    def _open_channel(self, servo_cfg, label):
        channel = servo_cfg.get("pwm_channel")
        if channel is None:
            raise ValueError(f"servos.json: {label}.pwm_channel muss gesetzt sein")
        bcm_pin = int(servo_cfg.get("pin", -1))
        pin_channels = {12: 0, 13: 1}
        if bcm_pin not in pin_channels or int(channel) != pin_channels[bcm_pin]:
            raise ValueError(
                f"Falsche BCM/PWM-Zuordnung fuer {label}: GPIO{bcm_pin}, Kanal {channel}; "
                "Pi 4 PWM0=GPIO12/Kanal0, PWM1=GPIO13/Kanal1"
            )
        pwm = HardwarePwmChannel(self.pwm_chip, channel, self.period_ns, self.log)
        self.log(f"Servo {label}: Hardware-PWM auf GPIO{bcm_pin}, Kanal {channel}")
        return pwm

    def _angle_to_pulse(self, angle):
        angle = self._clamp_angle(angle)
        span = max(1e-9, self.angle_max - self.angle_min)
        fraction = (angle - self.angle_min) / span
        return self._clamp_pulse(
            self.pulse_min_us + fraction * (self.pulse_max_us - self.pulse_min_us)
        )

    def _wait(self, duration):
        return self._stop.wait(max(0.0, duration))

    def _run_servo1(self, pulse_us, duration_sec, action):
        pulse_us = self._clamp_pulse(pulse_us)
        duration_sec = max(0.0, float(duration_sec))
        self.log(f"Servo1 {action}: Puls {pulse_us:.0f}us fuer {duration_sec:.2f}s")
        try:
            self._servo1.set_pulse_us(pulse_us)
            self._wait(duration_sec)
        finally:
            self._servo1.set_pulse_us(self.servo1_stop_pulse_us)

    def _run_servo1_until_load_neutral(self, pulse_us, action):
        with self._lock:
            load_is_active = self._load_switch_active
        if not load_is_active:
            self.log(f"Servo1 {action}: LOAD switch is already neutral; motor not started")
            return

        deadline = time.monotonic() + self.servo1_eject_max_run_sec
        self.log(
            f"Servo1 {action}: running until LOAD switch is neutral "
            f"(safety limit {self.servo1_eject_max_run_sec:.1f}s)"
        )
        try:
            self._servo1.set_pulse_us(self.servo1_eject_pulse_us)
            while not self._stop.is_set() and not self._load_neutral.is_set():
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    self.log(f"Servo1 {action}: safety timeout before LOAD switch became neutral")
                    break
                self._load_neutral.wait(min(0.05, remaining))
        finally:
            self._servo1.set_pulse_us(self.servo1_stop_pulse_us)
        if self._load_neutral.is_set():
            self.log(f"Servo1 {action}: stopped when LOAD switch returned to neutral")

    def _move_servo2(self, target_angle):
        target = self._clamp_angle(target_angle)
        pulse_target = self._angle_to_pulse(target)
        if self.servo2_angle is None:
            self.log(f"Servo2 erste Position: {target:.1f} Grad (Startposition unbekannt)")
            self._servo2.set_pulse_us(pulse_target)
            self.servo2_angle = target
            self._wait(self.first_move_settle_sec)
            duration = self.first_move_settle_sec
        else:
            start = self.servo2_angle
            distance = abs(target - start)
            if distance <= 0.5:
                self._servo2.set_pulse_us(pulse_target)
                duration = self.servo_settle_sec
                self._wait(duration)
            else:
                frame_sec = 1.0 / self.frequency_hz
                if self.servo2_speed_deg_per_sec and self.servo2_speed_deg_per_sec > 0:
                    smooth_factor = 1.5 if self.servo2_smooth_ramp else 1.0
                    target_duration = (
                        distance * smooth_factor / self.servo2_speed_deg_per_sec
                    )
                    steps = max(1, math.ceil(target_duration / frame_sec))
                else:
                    steps = 1
                start_time = time.monotonic()
                for index in range(1, steps + 1):
                    if self._stop.is_set():
                        break
                    progress = index / steps
                    if self.servo2_smooth_ramp:
                        progress = progress * progress * (3.0 - 2.0 * progress)
                    angle = start + (target - start) * progress
                    self._servo2.set_pulse_us(self._angle_to_pulse(angle))
                    deadline = start_time + index * frame_sec
                    self._wait(max(0.0, deadline - time.monotonic()))
                duration = time.monotonic() - start_time
                self.servo2_angle = target
                if self.servo_settle_sec:
                    self._wait(self.servo_settle_sec)
                    duration += self.servo_settle_sec

        if self.release_after_move:
            self._servo2.disable()
        return duration

    def _run_eject_sequence(self):
        started = time.monotonic()
        self.log("Servo eject sequence started")

        def run_door():
            try:
                open_duration = self._move_servo2(self.servo2_open_angle)
                self._wait(max(0.0, self.eject_door_open_hold_sec - open_duration))
                if not self._stop.is_set():
                    self._move_servo2(self.servo2_closed_angle)
            except Exception as exc:
                self.log(f"Servo2 door sequence failed: {exc}")

        def run_eject():
            try:
                if not self._wait(self.eject_door_delay_sec):
                    self._run_servo1_until_load_neutral(self.servo1_eject_pulse_us, "eject")
            except Exception as exc:
                self.log(f"Servo1 eject sequence failed: {exc}")

        door_worker = threading.Thread(target=run_door, name="servo-door")
        eject_worker = threading.Thread(target=run_eject, name="servo-eject")
        door_worker.start()
        eject_worker.start()
        door_worker.join()
        eject_worker.join()
        self.log(f"Servo eject sequence finished ({time.monotonic() - started:.2f}s)")

    def _run_boot_eject_sequence(self):
        started = time.monotonic()
        self.log("Servo boot eject sequence started")
        self._move_servo2(self.servo2_open_angle)
        if not self._wait(self.boot_step_delay_sec):
            self._run_servo1_until_load_neutral(self.servo1_eject_pulse_us, "boot eject")
        if not self._wait(self.boot_step_delay_sec):
            self._move_servo2(self.servo2_closed_angle)
        self.log(f"Servo boot eject sequence finished ({time.monotonic() - started:.2f}s)")

    def _run_load_sequence(self):
        started = time.monotonic()
        self.log(
            f"Servo1 load: running until LOAD_STOP endstop, "
            f"safety limit {self.servo1_load_max_run_sec:.1f}s"
        )
        try:
            self._servo1.set_pulse_us(self.servo1_load_pulse_us)
            deadline = started + self.servo1_load_max_run_sec
            while not self._stop.is_set() and not self._load_endstop.is_set():
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    self.log("Servo1 load safety timeout reached before LOAD_STOP")
                    break
                self._load_endstop.wait(min(0.05, remaining))
        finally:
            self._servo1.set_pulse_us(self.servo1_stop_pulse_us)
        if self._load_endstop.is_set():
            self.log(f"Servo1 load stopped by endstop ({time.monotonic() - started:.2f}s)")
        self.log(f"Servo load sequence finished ({time.monotonic() - started:.2f}s)")

    def _start_sequence(self, sequence, label):
        with self._lock:
            if self._busy:
                self.log(f"Servo {label} ignored: another sequence is active")
                return False
            self._busy = True
            self._sequence_label = label
            self._stop.clear()

            def run():
                try:
                    sequence()
                except Exception as exc:
                    self.log(f"Servo {label} sequence failed: {exc}")
                finally:
                    with self._lock:
                        self._busy = False
                        self._sequence_label = ""
                        self._worker = None

            self._worker = threading.Thread(target=run, name=f"servo-{label}", daemon=True)
            self._worker.start()
            return True

    def trigger_eject(self):
        with self._lock:
            active_worker = self._worker if self._busy and self._sequence_label != "eject" else None
            if active_worker is not None:
                self.log("Eject requested during another servo sequence; stopping it first")
                self._stop.set()
            elif self._busy:
                self.log("Servo eject ignored: eject sequence is already active")
                return False
        if active_worker is not None:
            active_worker.join()
        return self._start_sequence(self._run_eject_sequence, "eject")

    def trigger_boot_eject(self):
        return self._start_sequence(self._run_boot_eject_sequence, "boot-eject")

    def set_load_switch_active(self, active):
        with self._lock:
            self._load_switch_active = bool(active)
            if active:
                self._load_neutral.clear()
            else:
                self._load_switch_consumed = False
                self._load_neutral.set()

    def set_load_endstop_active(self, active):
        active = bool(active)
        with self._lock:
            was_active = self._load_endstop_active
            self._load_endstop_active = active
            is_loading = self._busy and self._sequence_label == "load"
            if active and is_loading:
                self._load_endstop.set()
        if active and is_loading and not was_active:
            self.log("LOAD endstop active; immediately sending servo neutral pulse")
            self._servo1.set_pulse_us(self.servo1_stop_pulse_us)

    def trigger_load(self, switch_active=False, endstop_active=False):
        with self._lock:
            if switch_active and self._load_switch_consumed:
                self.log("Servo load ignored: LOAD switch activation was already handled")
                return False
            if not switch_active and self._load_switch_active:
                self.log("Servo load ignored: LOAD switch is still active")
                return False
            if switch_active:
                self._load_switch_active = True
                self._load_switch_consumed = True
                self._load_neutral.clear()
            if endstop_active or self._load_endstop_active:
                self.log("Servo load ignored: LOAD_STOP endstop is already active")
                return False
            self._load_endstop.clear()
        return self._start_sequence(self._run_load_sequence, "load")

    def stop_load(self):
        with self._lock:
            if self._busy and self._sequence_label == "load":
                self._load_endstop.set()
                return True
        return False

    def close(self):
        self._stop.set()
        worker = self._worker
        if worker is not None and worker is not threading.current_thread():
            worker.join()
        for channel in (self._servo1, self._servo2):
            if channel is not None:
                try:
                    channel.close()
                except Exception as exc:
                    self.log(f"Servo PWM shutdown failed: {exc}")
        self._servo1 = None
        self._servo2 = None